### ISSUE TITLE
default radio checked with HTML instead of JS

### ISSUE THREAD

**Issue by cunnellp5** [Payton212/SKATE#1]
Instead of waiting for the page to load and then setting the easy radio button to checked with JS we could just add the checked attribute to the html, so that one is always defaulted as the selected mode

- would clean up the js file and not have to wait for the window to load (line 20-22)
- allow html to handle the default

**Comment by Payton212** [comment]
un aware of this i do like that! how would you implement this?

**Comment by cunnellp5** [comment]
when you use JS to set the checked attribute to 'true'

```
window.onload = function () {
  dEasy.checked = true;
};
```

its the same thing as doing

```
<div>
  <label for = "easy">
  <input 
      type = "radio" 
      name = "difficulty" 
      value = "easy" 
      id = "easy"
      checked <<<<<<<<< adding this 'attribute' in the HTML does the same thing
      /> 
      Easy 
  </label>
</div>
```

or another way is to use the 'setAttribute' method in JS

Usually you can see this update in the browser if you click a check box / radio button, but since this is a static page, you wont be able to inspect and observe the changes, which makes it a little confusing because setting it from JS wont show up in the DOM

This change doesn't make a difference in the program, but I think not having to update the DOM on `window.onload` makes life slightly easier

**Comment by Payton212** [comment]
will push this up with the edited random functions!
