### ISSUE TITLE
consolidate random functions

### ISSUE THREAD

**Issue by cunnellp5** [Payton212/SKATE#2]
looking at 

```
function gRandomStance(stances) {
  return stances[Math.floor(Math.random() * stances.length)];
}
function gRandomDirection(directions) {
  return directions[Math.floor(Math.random() * directions.length)];
}
function gRandomRotations(rotations) {
  return rotations[Math.floor(Math.random() * rotations.length)];
}
function gRandomShuvs(shuvs) {
  return shuvs[Math.floor(Math.random() * shuvs.length)];
}
function gRandomFlip(flips){
  return flips[Math.floor(Math.random() * flips.length)];
}
```

these are all doing the same thing, is there a way to consolidate these such that you'd only call one function?

**Comment by Payton212** [comment]
Absolutely it is true you don't need the names to match to transfer the data?

**Comment by cunnellp5** [comment]
nope!

You could use any one of those 5 functions as is and call them from above and you'd get the same result.

As long as you're passing different arguments, the function parameters can be the same. Only because stances, directions, rotations, shuvs, and flips are all arrays

so for example this would still work:
```js
randomStance = gRandomStance(stances);
randomDirection = gRandomStance(directions);
randomRotation = gRandomStance(rotations);
randomFlip = gRandomStance(flips);
randomShuvs = gRandomStance(shuvs);
```

so by just using one function you can clean things up. 
I'm having trouble thinking of a better function name and function parameters, but one example could be:

```js
function getRandomSkateConfig (skateConfig) {
    return skateConfig[Math.floor(Math.random() * skateConfig.length)];
}
```

fwiw the function parameter `skateConfig` can be any word you like, because its just a placeholder for what you're calling the function with. As long as you're giving it an array the function should do what's expected

**Comment by Payton212** [comment]
will push this up in just a bit but i was able to quickly get this in before i was told to get off😂
