### ISSUE TITLE
scalable mapping instead of if/else

### ISSUE THREAD

**Issue by cunnellp5** [Payton212/SKATE#3]
looking at the large if/else to determine the trick isnt very scalable, and would be hard to debug

```
    if(newTrick.stance === 'regular' && newTrick.direction === 'frontside' && newTrick.rotation === '180' && newTrick.shuv === 'none' && newTrick.flip === 'none'){
         namedTrick = 'front 180';
    }else if(newTrick.stance === 'regular' && newTrick.direction === 'frontside' && newTrick.rotation === 'none' && newTrick.shuv === '180' && newTrick.flip === 'none'){
        namedTrick = 'front shuv';   
        ... etc
```

This could be a good use case for mapping data, getting rid of conditionals, which then reduces 'cyclomatic complexity'

one example of mapping data could look like:

```
trickMapper = {
 'regular_frontside_180_none_none': 'front 180'
}

namedTrick = trickMapper[`${stance}_${direction}_${rotation}_${shuv}_${flip}`]
```

While i think it might be messy to use strings like this, i cant think of a clean way to use some nested object structure in a smart way. But i think it could grow a little easier as the medium and hard tricks come thru. Plus you can then get rid of all if/else

**Comment by Payton212** [comment]
i was un aware this was possible i really like the layout and reusability of the code will definitely look into implementing this!!!

**Comment by cunnellp5** [comment]
Yeah any time you start doing an if/else chain, take a moment to think about if there could be ways around it.
They make sense and are necessary, but they can get out of control.

And often they can be removed with some sort of 'mapping' object or maybe the data could be restructured somehow

**Comment by Payton212** [comment]
absolutely! im looking forward to learning more about it and learning to implement it!

**Comment by Payton212** [comment]
im trying to implement it and im not entirely sure how to pass the data to TrickMapper
/* 
    let newTrick = easy(skateConfig);
    trickMapper = {
    'regular_frontside_180_none_none'
    } 
    namedTrick = trickMapper[`${stance}_${direction}_${rotation}_${shuv}_${flip}`];
    */ 

 would it be more like 

/* 
    let newTrick = easy(skateConfig);
    trickMapper = {
    'regular_frontside_180_none_none'
    } 
    namedTrick = trickMapper[`${skateConfig.stance}_${skateConfig.direction}_${skateConfig.rotation}_${skateConfig.shuv}_${skateConfig.flip}`];
    */   if not this then im unsure how to pass the knowledge

**Comment by Payton212** [comment]
okay i see you had it exactly how it was supposed to be 🤦🏻‍♂️

**Comment by Payton212** [comment]
pushed up the trick mapper code!
