### ISSUE TITLE
skate config for each level

### ISSUE THREAD

**Issue by cunnellp5** [Payton212/SKATE#4]
inside the easy function, it looks like the easy mode config is chosen at random. What if there was an object at the top that looked something like

```
skateconfig = {
  easy: {},
  medium: {},
  hard: {}
}
```

then you could destructure the vars from the obj inside each difficulty. and have the config values at the top of the file which would be easier to read

**Comment by Payton212** [comment]
i may need you to explain a little the purpose of this but if i understand i have easy to be automatically set to true onload unless it's changed to prevent an invalid value

**Comment by Payton212** [comment]
okay after reading the rest of the issues i see you know about the onload, so i guess i am unsure what the the question is

**Comment by cunnellp5** [comment]
This was just a thought about structuring the easy, medium, hard modes in a readable way, but totally up for discussion if you're not feeling it.

I was thinking, 
since you've got all the constant array variables up at the top of the file, then when you hit your `easy()` function you're then determining which pieces of the vars to use. 

Ultimately, lines 12-16 aren't used in the program. 

So I was wondering what if they could be used and how? 
So I was wondering if it would make sense to replace lines 12-16 with an object like this:

```js
const skateConfig = {
  easy: {
    stances: ["regular", "fakie"],
    directions: ["frontside", "backside"],
    rotations: ["180", "none"],
    flips: ['kickflip', 'heelflip', 'none'],
    shuvs: ['180','none']
  },
  medium: {...},
  hard: {...}
}
```

Then when you call the easy function you can just grab or 'destructure' the 'easy mode vars' like this:

```js
const { stances, directions, rotations, flips, shuvs } = skateConfig.easy;
```

This is cool because you now have one place to change the easy/medium/hard configurations

You could probably even take that a step further and put the `completedTrick` inside the easy, medium and hard sections to keep track of all three separately.

And then you could probably take that EVEN further and build an array of `namedTricks` and check for uniqueness against a string of tricks rather then each type of trick (flip, stance, direction, rotation, and shuv) like you're doing in the do/while

And then you could probably take that EVEN FURTHER by considering using a set instead of an array, if you need to check for uniqueness of a list - this is a stretch goal, arrays are fine, but if you need a list of unique items, a 'Set' is a powerful data type. Sets are funky and hard to 'see' with console logs, so don't stress about it if you decide to go down that path

**Comment by Payton212** [comment]
no I love that idea! a way to organize the code a little better i have a feeling im going to run into issues with this so i may need help debugging but but i love the idea and this is the definitely what i need to improve on so anytime you see something like this don't hesitate to point it out!
