### ISSUE TITLE
do while

### ISSUE THREAD

**Issue by cunnellp5** [Payton212/SKATE#5]
can you talk me through what the do while loop is doing inside the easy function?

**Comment by Payton212** [comment]
it's rerunning the function to find an array that hasn't been created yet so tricks don't repeat, essentially stops arrays from duplicating

**Comment by cunnellp5** [comment]
I see now, thats a good trick!

It took a few minutes to really understand the intention behind what thats doing. And I think breaking something that looks a little tricky into smaller functions that explain whats going on is a really powerful pattern.

I'm assuming you'll check uniqueness for the medium and hard modes, and having this do/while in a reusable function could be helpful for the near future

While i do think the data could be massaged to be slightly simpler, it could be a good practice to 

1. replace the entire do/while loop with a function that is clearly named; something like `function generateUniqueTrick() {...}`
2. the do and the while blocks could be separate functions themselves to clearly talk about what they're doing too, like

```js
 generateUniqueTrick() {
    do {
        const newTrickObj = createNewTrick()
    } while (trickHasNotBeenUsed(newTrickObj))
    
    return newTrickObj;
}
```

This makes reading the code more like reading a sentence and is better for testing, scalability, and debugging

**Comment by Payton212** [comment]
again going back to helping organize and reuse code is a big thing i need to work on so i will try an d get this in before work!
will also make implementing medium and hard a lot easier!

**Comment by Payton212** [comment]
i do think ill need a bit more explanation of how to use this but i do love the idea

**Comment by cunnellp5** [comment]
i was about to make a PR but i went way to hard on it. So I'm going to build some what of a check list of things i would do here:

This might sound like a lot and maybe a little bit crazy, but hang in there with me for this

lets start with a little bit of clean up to make moving forward slightly easier:
- [ ]  put const in front of the trickMapper
- [ ] move the trickMapper to the top of the file, near skateConfig - since this is a const it can be globally scoped
- [ ] i want you to replace lines 69-91 with a single function, i want the whole 'easy()' to look really small like this:

```js
function easy(skateConfig) {
  if (completedTricks.length === 12) {
    return `all tricks generated`;
  }
  return generateUniqueSkateConfig(skateConfig.easy);
}
```

and the new function might look something like

```js
function generateUniqueSkateConfig(config) {
  let randomConfig;
  do {
    randomConfig = randomGenerator(config);
   } while (checkIfTrickHasBeenDone(randomConfig));

  return randomConfig;
}
```

These are suggestions i haven't fully tested, but it should run the same as before. I've left out a lot of stuff for you to explore, but i want to try and fuel your fire here. Fwiw, dont bang your head on this, because it could entirely change in the near future. But i think its good practice to re build things into smaller functions

Thoughts:
1. i think renaming the easy() function to something more verbose might be worth while - like `createEasyTrickConfig()`
2. I think pushing to the `completedTricks` array should happen somewhere else. Because right now the easy fucntion is doing 2 things, 1. generating some stance config and 2 building the completedTrick array. To me it makes a little more sense to give the function 1 task and then handle building stuff all at the same time, like in the click
3. I think it would be cool to add a completedTrick and named trick keys as empty arrays to the `skateConfig.easy` object - and i think keeping track of all the namedTricks would be cool to display some time in the future
4. I also think one coding trick to learn is 'destructuring' objects, I challenge you to destructure line 33, then update line 49 - 56

let me know if something doesnt make sense here, there's a lot and i think im leaving you with something to chew on for a minute - and i could have a typo or a mistake somewhere, just as a fair warning

**Comment by Payton212** [comment]
successfully implemented the suggested functions may need to relocate where the array is getting pushed

**Comment by Payton212** [comment]
after editing code thought 4 is no longer the same lines could you look back at them so i can give that a shot!!!

**Comment by cunnellp5** [comment]
the new line you could destructure would be 53 and / or 66
and then you would be able to update lines 56-63 then 69-76 respectively.

Can you see a pattern in those two blocks?

After destructuring, another challenge would be to see how you could consolidate these two blocks and move them out of the if/elses and do the textContent updates at the bottom of this function

**Comment by Payton212** [comment]
i'm so sorry i messed with the trick mapper since you posted this i won't be coding for the rest of the day if you want to tell me one last time I apologize for my negligence

**Comment by Payton212** [comment]
just pushed so you can see the code i currently have to update what lines you are mentioning

**Comment by cunnellp5** [comment]
its ok!

its where it says `let newTrick` so right now its 70 and 83

ps. right click in the JS file and click the "Format Document"

**Comment by cunnellp5** [comment]
nicely done
