### ISSUE TITLE
Duplicate randomGenerator functions

### ISSUE THREAD

**Issue by cunnellp5** [Payton212/SKATE#7]
I really like how you broke the do while loop apart, nice work!

Can you talk me through the difference between the `easyRandomGenerator` and the `mediumRandomGenerator` functions? I'm having trouble understanding the shuv logic

They appear to be doing mostly the same stuff, and i think there's room to consolidate those. But I think there might be some nuance to said shuv logic that im not gettinge

**Comment by Payton212** [comment]
So in easy I have shuv set to be the opposite of rotation and if k/h is none then shuv can be 180 cause I wouldn’t think a big spin or varial flips should be in easy and medium is attempting get any combination other than ‘regular_none_none_none_none’
‘Regular_frontside_none_none_none’
‘Regular_none_none_180_none’
And the variations of those because they aren’t tricks maybe there is a way to exclude those from being options so we can use the same logic and if it’s not one of those we push it to the array!!!

**Comment by cunnellp5** [comment]
okok yeah. i think i got it, going to think about how this is being structured.
my spidey sense is tingling because im seeing duplicate functionality, and the shuv logic is throwing me off

Its making me wonder why we're generating tricks based on all the config stuff. It seems like that's the hard way of figuring out what a trick is.

---

I hate to ask this question but i'm wondering if the generation of a trick logic would make sense if the idea was turned around? Because whats seen on the screen wouldnt change, but the logic might be cleaner. As in why not have a list of easy - hard tricks, and why not choose those randomly. Then based on those display a list of config values.. You're sort of already doing this but in reverse. And doing it this way could eliminate all logic

1. Click the button
2. Randomly grab an 'easy' trick lets say ollie
3. Then based on that show the user what the body / board has to do to achieve that?

What if there was two sections to the application where you could 

1. Generate a trick of any difficulty >>> this feels like what the app wants to be
2. Pick and choose different set ups to see what a trick might be? >>> this feels like what we're building right now

**Comment by Payton212** [comment]
You’re definitely right I was just thinking it might be easier to have the base done this way so when we add in rails and hubbas and stuff we can just piggy back off of this instead of just outright naming everything but what do you think? Which would make more sense to you??

**Comment by Payton212** [comment]
cause my original idea for the app is basically like you create a game by selecting the obstacle like rails or hubbas or euros and depending on whats selected with what difficulty those tricks are what are generated
idk if that makes sense

**Comment by cunnellp5** [comment]
Can you outline all the features you'd like this application to have in the form of user stores?

something like this format: 

```
A typical user story follows the format "As a [persona], I want to [software goal], so that [result]"
```

---

For our case a few could be like:

***for all the following stores we can implly if an optional value is not set, it will be randomly generated***

- users can optionally set the stance, so that when a trick is generated the set stance is considered 
- users can optionally set the direction, so that when a trick is generated the direction is considered
...

This should be a lot of repeated stuff, but if we can outline all the features right now, it could maybe help inform how we might want to structure the data.
This is also good practice for actual feature planning when you'll be employed

**Comment by cunnellp5** [comment]
maybe even put them in a readme as a checklist?

**Comment by Payton212** [comment]
yes i will do that when home from work!

**Comment by Payton212** [comment]
a great opportunity to test the readme generator!!

**Comment by Payton212** [comment]
has succesfully created a readme to better show what i am trying to accomplish with this project

**Comment by cunnellp5** [comment]
please format your documents using your editor

**Comment by Payton212** [comment]
I’ll send you a picture of what happens when I do on LinkedIn

**Comment by cunnellp5** [comment]
you can paste pictures here easier

**Comment by Payton212** [comment]
Uploading IMG_8725.mov…

**Comment by Payton212** [comment]
https://github.com/user-attachments/assets/11b3b293-ff83-467e-a591-76c3db8d1e27

**Comment by cunnellp5** [comment]
Couldnt push changes to open a PR but heres a version i think is a little easier to read, thanks for writing this, i think it should help inform how you'd like to build the skate data

[README.md](https://github.com/user-attachments/files/18276448/README.md)

**Comment by Payton212** [comment]
downloaded will push definatley prefer this layout!

**Comment by Payton212** [comment]
and why wouldn't it let you push?
do you need more authorization or something do i  need to adjust the settings

**Comment by cunnellp5** [comment]
i dont think i made a fork of it first. which i could try

**Comment by Payton212** [comment]
i merged the pr request so we should be good

**Comment by cunnellp5** [comment]
nice! ok considering we might be moving towards a different data structure and how this works. I imagine the do/while will go away. Closing this issue
